### ISSUE TITLE
Feature request: web backend

### ISSUE THREAD

**Issue by ten3roberts** [DouglasDwyer/wasm_runtime_layer#1]
The web backend would make use of the WebIDL webassembly API such as [WebAssembly.instantiate](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiate) and other apis for instantiation, and use the javascript buffer apis for writing to and from the linear memory during marshalling.

Related issue: https://github.com/AmbientRun/Ambient/issues/1131

I will work on implementing this and open a draft PR shortly. Feel free to add questions or comments

**Comment by DouglasDwyer** [comment]
One thing to consider with this is that the web APIs require that module creation and instantiation happens `async`. The runtime layer does not presently have async methods for this use case. They will need to be added; I know of no way around this.

**Comment by ten3roberts** [comment]
I think I have a solution in mind for that issue. After all, that is one of the many footguns I've been dealing with when porting Ambient to the web.

A more prominent issue however is Send and Sync, since any JsValue (and therefore WebAssembly.Instance and functions) are inherently *not Send nor Sync*, but it is required by the traits and AnyCloneBoxed.

Do you have any suggestions or workarounds you would be ok with in regards to the send and sync issue?

**Comment by DouglasDwyer** [comment]
The Send and Sync issue is definitely a tough one. Luckily, I think that there's an easy way to move forward.

The types `Engine<E>` and `Store<E>` are generic, and thus can be made to be Send/Sync only when `E` is Send/Sync. All other types require a reference to their associated `Engine`/`Store` in order to call methods on them. Therefore, we should be able to `unsafe impl Send + Sync` on all other objects in the web backend, provided we check beforehand that the engine/store argument is correct before method calls. Does that make sense? It should be a non-intrusive way to go.

**Comment by ten3roberts** [comment]
Was going to post a list of my ideas, but you pretty much nailed it. I've diven into the code and it does seem like all methods I need get passed the store, so for now I am storing ids inside the Instance, Module, etc; while the actual JsValue of them lives in a Slab inside the Store.

To solve this in Ambient within our ECS unsafe impl Send + Sync for all these and promised to never send them across threads manually, which is definitely not a solution in a public API.

As for the dropping, there are two approaches. We can use a flume channel and send a "hey destroy this index" when the remote type is dropped, or we can forego cleanup until the store is dropped, which is what I believe wasmtime does.

This means that the Stores items and modules should have an equal lifespan and not mixed to avoid infinite growth, but this is something that wasmtime already states in their API for the same reason, so we can ferry on that.

Bubbling the engine marker all the way to the wasm_component_layer boundary is definitely leaky, and is in my experience often a grave mistake and just leads to more generic leakage downstream, and I have in other libraries removed such generics and internalized them as they became so unwieldy, especially if a user needs to box it.

**Comment by DouglasDwyer** [comment]
That seems fair. I think `wasmi` also handles it similarly, so if it's easiest then let's go with cleanup when the store and engine are dropped. Glad to hear that we are on the same page!

**Comment by ten3roberts** [comment]
One issue I have encountered is regarding internal mutability of the stores.

In order to call functions from the spawned module I need to provide a js function to call. It needs to capture the store so that it can be used in the host side body of the function, since it can be called whenever. As such, I need to wrap my store in a Rc<RefCell>, in order to share it across the js boundary and wasm-bindgen's function table.

The issue with this is that the `data` and `data_mut` methods on `WasmStore` can't be implemented, as the data is tucked away beneath a `Ref<'_, T>`.

They *can* be implemented for `WasmStoreContext` and `WasmStoreContextMut` as they already contain the borrowed guard in `self` and I can simply return the reference.

To fix this I can either modify the traits to encompass a GAT guard associated type which returns a guard which implements `Deref<Target = T>`, or remove the `data` and `data_mut`, and possibly the `engine` method from `WasmStore` and provide them through the "borrowed" or "mutex locked" `StoreContext` and `StoreContextMut` instead.

Both these solutions would require modifying `wasm_component_layer` as well to do `store.as_context().data()` or

```
let ctx = store.as_context();
ctx.data
```

etc

Which is essentially the equivalent of the `acquire lock and access` pattern.

`wasmi` gets around this issue by running in a read-eval loop which always has the store as a local argument.

`wasmtime` uses unsafe code to provide a raw pointer in its wrapped function to reconstruct the store when the function is called in the JIT executed machine code, and then carefully ensuring that the guest functions only live as long as the store and not access the pointer after the store is dropped.

Are you ok with modifying the traits and possibly opening a correlated PR to `wasm_component_layer`?

**Comment by DouglasDwyer** [comment]
What about something like this?

```rust
struct Store<T> {
   data: Option<Box<T>>,
   shared_data: Rc<RefCell<Option<Box<T>>>>
}
```

When the store is floating around freely, the user data sits in the `data` member and can be accessed by reference. Whenever it comes time to invoke a WASM function, the store moves the data into the `shared_data` member where it sits for the duration of the call. I think that this would do the trick, without having to modify the public facing API.

---

Overall, I'm open to either solution - the one presented above, or just removing the `data` methods from `Store` altogether. They're not truly necessary, and I suppose I added them to best match the `wasmtime` API. Choose the one that you think is most appropriate - although as you observed, modifying the traits will also require a downstream PR for the component crate.
