### ISSUE TITLE
`wasmi::Module` does not need to be wrapped in `Arc`, or does it?

### ISSUE THREAD

**Issue by Robbepop** [DouglasDwyer/wasm_runtime_layer#25]
Wasmi's `Module` already internally is an `Arc`, so wrapping it in an `Arc` has no real benefits, or am I overlooking something?
https://docs.rs/wasmi/0.39.1/src/wasmi/module/mod.rs.html#53-55

Concerning: https://docs.rs/wasmi_runtime_layer/0.39.0/wasmi_runtime_layer/struct.Module.html

Given that `wasmtime_runtime_layer::Module` is not an `Arc` wrapper:
https://docs.rs/wasmtime_runtime_layer/26.0.0/wasmtime_runtime_layer/struct.Module.html

**Comment by DouglasDwyer** [comment]
You are correct - the `Arc` wrapper is left over from earlier versions of `wasmi`, where the `Module` structure was not itself `Clone`. I have pushed a fix to main - it will be included in the next version of `wasmi_runtime_layer`. Thanks!
